name: Update Publications

on:
  schedule:
    # Run on the 1st of each month at 2:00 AM UTC
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Allow manual triggering for testing
  push:
    branches: [ src, main, master ]  # Run on push to these branches for testing

jobs:
  update_publications:
    runs-on: ubuntu-latest
    name: 'Update Publications from Google Scholar'
    
    permissions:
      contents: write  # Allow the workflow to commit changes
      
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run publication update script
      run: |
        cd scripts
        python update_publications_smart.py --file ../out_scholar.bib --verbose
        
    - name: Check for changes
      id: verify_diff
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify_diff.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add out_scholar.bib
        git commit -m "Auto-update publications from Google Scholar [$(date +'%Y-%m-%d')]"
        git push
        
    - name: Create summary
      run: |
        echo "## Publication Update Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Date**: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "- **Changes**: ${{ steps.verify_diff.outputs.changes }}" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.verify_diff.outputs.changes }}" == "true" ]; then
          echo "- **Status**: ✅ Publications updated successfully" >> $GITHUB_STEP_SUMMARY
        else
          echo "- **Status**: ℹ️ No changes detected" >> $GITHUB_STEP_SUMMARY 